### ISSUE TITLE
Texting instead of emailing?

### ISSUE THREAD

**Issue by cblavier** [zanderxyz/veil#13]
Nice project, I love how simple it is!

I was wondering how complex it would be to text the secure link to some users instead of emailing them? Each user should be able to either login with its email or phone number

**Comment by zanderxyz** [comment]
Hi,

You can definitely do this but there'd be some costs involved to handle the texting. [Twilio](https://www.twilio.com/) offers a paid API for sending SMS messages and there is an [Elixir API Client](https://github.com/danielberkompas/ex_twilio). 

To integrate with Veil, you would need to change the `send_link_email` function in veil.ex to send a text message using the Twilio API instead of an email. In the existing implementation you can see this part generates the sign in link: `new_link_url(conn, request.unique_id)`.

I'd say it's probably not worth integrating this into Veil, given the work is mostly setting up the Twilio API etc - changing the `send_link_email` function is trivial once that part is done.

**Comment by niahoo** [comment]
Great idea.

Maybe just providing a way to override the function call through mix config ?

**Comment by cblavier** [comment]
I guess there would be also some work involved in identifying users not only with their email address but also with their phone number

**Comment by niahoo** [comment]
Phone number could be fetched with help of the email, but I guess some apps would not store any email so yes ... it could be better to have an actual implementation to look at before going further.

**Comment by zanderxyz** [comment]
You're correct that you'd have to identify by phone number, so phone numbers entered as a string would need to be parsed into E164 format and then saved as a string. I know that libraries exist in other languages for this (e.g. PhoneNumberKit for Swift) but might not for Elixir yet.

**Comment by matthewford** [comment]
There is https://github.com/madebymany/passwordless_auth for sms.
